server:
  port: 80

spring:
  application:
    name: consul-consumer-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      instance:
        prefer‐ip‐address: true #可以跨域访问
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug
